name: flutter_story_app
description: Story App build using firebase.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  file_picker: ^5.2.11
  dotted_border: ^2.0.0+3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true